---
name: Buid
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Go checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Go build
        run: make

      - uses: actions/upload-artifact@master
        with:
          name: spectator
          path: dist/spectator
...
